import 'package:boxing/core/constants/round_templates.dart';
import 'package:boxing/features/sessions/domain/session_model.dart';

class PresetSessions {
  PresetSessions._();

  static const List<SessionModel> all = [
    SessionModel(
      id: 'preset_pro_boxing_men',
      name: 'Pro Boxing (Men)',
      rounds: 12,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_pro_boxing_women',
      name: 'Pro Boxing (Women)',
      rounds: 10,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_amateur_boxing',
      name: 'Amateur Boxing',
      rounds: 3,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_amateur_women',
      name: 'Amateur Women',
      rounds: 3,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_shadow_boxing',
      name: 'Shadow Boxing',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 30,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_heavy_bag',
      name: 'Heavy Bag',
      rounds: 8,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_speed_bag',
      name: 'Speed Bag',
      rounds: 6,
      roundDurationSec: 120,
      restDurationSec: 30,
      warningTimeSec: 5,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_sparring',
      name: 'Sparring',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_pad_work',
      name: 'Pad Work',
      rounds: 4,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_conditioning',
      name: 'Conditioning',
      rounds: 10,
      roundDurationSec: 30,
      restDurationSec: 30,
      warningTimeSec: 5,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_tabata',
      name: 'Tabata',
      rounds: 8,
      roundDurationSec: 20,
      restDurationSec: 10,
      warningTimeSec: 0,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_emom',
      name: 'EMOM',
      rounds: 10,
      roundDurationSec: 60,
      restDurationSec: 0,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_beginner',
      name: 'Beginner',
      rounds: 4,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_youth_boxing',
      name: 'Youth Boxing',
      rounds: 4,
      roundDurationSec: 90,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_muay_thai',
      name: 'Muay Thai',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 120,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_mma',
      name: 'MMA',
      rounds: 3,
      roundDurationSec: 300,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    SessionModel(
      id: 'preset_kickboxing',
      name: 'Kickboxing',
      rounds: 3,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
    ),
    // --- Compound Round Presets ---
    SessionModel(
      id: 'preset_offense_defense',
      name: 'Offense / Defense',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      roundTemplate: RoundTemplates.offenseDefense,
    ),
    SessionModel(
      id: 'preset_bag_conditioning',
      name: 'Bag + Conditioning',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      roundTemplate: RoundTemplates.bagConditioning,
    ),
    SessionModel(
      id: 'preset_burnout',
      name: 'Burnout Rounds',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      roundTemplate: RoundTemplates.burnoutFinisher,
    ),
  ];
}
