import 'package:boxing/core/constants/round_templates.dart';
import 'package:boxing/features/combos/domain/combo_callout_config.dart';
import 'package:boxing/features/sessions/domain/session_model.dart';

class BoxingPresets {
  BoxingPresets._();

  static const List<SessionModel> all = [
    // --- Competition ---
    SessionModel(
      id: 'preset_boxing_pro_men',
      name: 'Pro Boxing (Men)',
      rounds: 12,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_boxing_pro_women',
      name: 'Pro Boxing (Women)',
      rounds: 10,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_boxing_amateur_men',
      name: 'Amateur Boxing (Men)',
      rounds: 3,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_boxing_amateur_women',
      name: 'Amateur Boxing (Women)',
      rounds: 3,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_boxing_youth',
      name: 'Youth Boxing',
      rounds: 3,
      roundDurationSec: 90,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'competition',
    ),

    // --- Training ---
    SessionModel(
      id: 'preset_boxing_shadow',
      name: 'Shadow Boxing',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 30,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'boxing',
        difficulty: 'beginner',
        intensity: 'moderate',
        includeDefense: true,
      ),
    ),
    SessionModel(
      id: 'preset_boxing_heavy_bag',
      name: 'Heavy Bag',
      rounds: 8,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'boxing',
        difficulty: 'intermediate',
        intensity: 'moderate',
      ),
    ),
    SessionModel(
      id: 'preset_boxing_speed_bag',
      name: 'Speed Bag',
      rounds: 6,
      roundDurationSec: 120,
      restDurationSec: 30,
      warningTimeSec: 5,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_boxing_sparring',
      name: 'Sparring',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_boxing_pad_work',
      name: 'Pad Work',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'boxing',
        difficulty: 'intermediate',
        intensity: 'moderate',
      ),
    ),
    SessionModel(
      id: 'preset_boxing_beginner',
      name: 'Beginner Boxing',
      rounds: 4,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'boxing',
        difficulty: 'beginner',
        intensity: 'relaxed',
      ),
    ),

    // --- Drills ---
    SessionModel(
      id: 'preset_boxing_offense_defense',
      name: 'Offense / Defense',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'drills',
      roundTemplate: RoundTemplates.offenseDefense,
    ),
    SessionModel(
      id: 'preset_boxing_bag_conditioning',
      name: 'Bag + Conditioning',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'drills',
      roundTemplate: RoundTemplates.bagConditioning,
    ),
    SessionModel(
      id: 'preset_boxing_burnout',
      name: 'Burnout Rounds',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'boxing',
      category: 'drills',
      roundTemplate: RoundTemplates.burnoutFinisher,
    ),
  ];
}
