import 'package:boxing/core/constants/round_templates.dart';
import 'package:boxing/features/combos/domain/combo_callout_config.dart';
import 'package:boxing/features/sessions/domain/session_model.dart';

class MuayThaiPresets {
  MuayThaiPresets._();

  static const List<SessionModel> all = [
    // --- Competition ---
    SessionModel(
      id: 'preset_mt_pro',
      name: 'Pro Muay Thai',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 120,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_mt_amateur',
      name: 'Amateur Muay Thai',
      rounds: 3,
      roundDurationSec: 120,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_mt_amateur_youth',
      name: 'Youth Muay Thai',
      rounds: 3,
      roundDurationSec: 90,
      restDurationSec: 45,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'competition',
    ),

    // --- Training ---
    SessionModel(
      id: 'preset_mt_pad_work',
      name: 'Thai Pad Work',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 120,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'muayThai',
        difficulty: 'beginner',
        intensity: 'moderate',
      ),
    ),
    SessionModel(
      id: 'preset_mt_heavy_bag',
      name: 'Thai Bag Work',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'muayThai',
        difficulty: 'intermediate',
        intensity: 'moderate',
      ),
    ),
    SessionModel(
      id: 'preset_mt_clinch',
      name: 'Clinch Work',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_mt_sparring',
      name: 'Muay Thai Sparring',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 120,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_mt_shadow',
      name: 'Thai Shadow Boxing',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 30,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'training',
      comboConfig: ComboCalloutConfig(
        enabled: true,
        sport: 'muayThai',
        difficulty: 'beginner',
        intensity: 'moderate',
        includeDefense: true,
      ),
    ),

    // --- Drills ---
    SessionModel(
      id: 'preset_mt_kick_drill',
      name: '100 Kicks Drill',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'drills',
      roundTemplate: RoundTemplates.mtKickDrill,
    ),
    SessionModel(
      id: 'preset_mt_clinch_knees',
      name: 'Clinch & Knees',
      rounds: 5,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'drills',
      roundTemplate: RoundTemplates.mtClinchKnees,
    ),
    SessionModel(
      id: 'preset_mt_elbow_combo',
      name: 'Elbows + Combos',
      rounds: 6,
      roundDurationSec: 180,
      restDurationSec: 60,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'muayThai',
      category: 'drills',
      roundTemplate: RoundTemplates.mtElbowCombo,
    ),
  ];
}
