import 'package:boxing/core/constants/round_templates.dart';
import 'package:boxing/features/sessions/domain/session_model.dart';

class BjjPresets {
  BjjPresets._();

  static const List<SessionModel> all = [
    // --- Competition ---
    SessionModel(
      id: 'preset_bjj_ibjjf_white',
      name: 'IBJJF White Belt',
      rounds: 1,
      roundDurationSec: 300,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_ibjjf_blue',
      name: 'IBJJF Blue Belt',
      rounds: 1,
      roundDurationSec: 360,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_ibjjf_purple',
      name: 'IBJJF Purple Belt',
      rounds: 1,
      roundDurationSec: 420,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_ibjjf_brown',
      name: 'IBJJF Brown Belt',
      rounds: 1,
      roundDurationSec: 480,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_ibjjf_black',
      name: 'IBJJF Black Belt',
      rounds: 1,
      roundDurationSec: 600,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_adcc_trials',
      name: 'ADCC Trials',
      rounds: 1,
      roundDurationSec: 360,
      restDurationSec: 0,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),
    SessionModel(
      id: 'preset_bjj_adcc_worlds',
      name: 'ADCC Worlds',
      rounds: 1,
      roundDurationSec: 600,
      restDurationSec: 0,
      warningTimeSec: 60,
      isPreset: true,
      sport: 'bjj',
      category: 'competition',
    ),

    // --- Training ---
    SessionModel(
      id: 'preset_bjj_rolling',
      name: 'Open Rolling',
      rounds: 6,
      roundDurationSec: 300,
      restDurationSec: 30,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_bjj_rolling_long',
      name: 'Long Rolls',
      rounds: 4,
      roundDurationSec: 480,
      restDurationSec: 60,
      warningTimeSec: 60,
      isPreset: true,
      sport: 'bjj',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_bjj_positional',
      name: 'Positional Sparring',
      rounds: 10,
      roundDurationSec: 180,
      restDurationSec: 15,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'bjj',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_bjj_shark_tank',
      name: 'Shark Tank',
      rounds: 8,
      roundDurationSec: 120,
      restDurationSec: 10,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'bjj',
      category: 'training',
    ),
    SessionModel(
      id: 'preset_bjj_drilling',
      name: 'Timed Drilling',
      rounds: 6,
      roundDurationSec: 300,
      restDurationSec: 30,
      warningTimeSec: 30,
      isPreset: true,
      sport: 'bjj',
      category: 'training',
    ),

    // --- Drills ---
    SessionModel(
      id: 'preset_bjj_guard_pass',
      name: 'Guard Passing Drill',
      rounds: 8,
      roundDurationSec: 180,
      restDurationSec: 15,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'bjj',
      category: 'drills',
      roundTemplate: RoundTemplates.bjjGuardPass,
    ),
    SessionModel(
      id: 'preset_bjj_sub_escape',
      name: 'Sub Defense Drill',
      rounds: 8,
      roundDurationSec: 120,
      restDurationSec: 15,
      warningTimeSec: 10,
      isPreset: true,
      sport: 'bjj',
      category: 'drills',
      roundTemplate: RoundTemplates.bjjSubEscape,
    ),
  ];
}
